### ISSUE TITLE
Differing min-layer-size between CLI and Index Builder

### ISSUE THREAD

**Issue by turan18** [aws-ia/cfn-ecr-aws-soci-index-builder#40]
## Problem
 
The SOCI CLI sets a 10 MiB [default](https://github.com/awslabs/soci-snapshotter/blob/ec1e62326578318ace5048c487b7e155a068dd4b/soci/soci_index.go#L58) `--min-layer-size` threshold when building indexes, which means layers under 10 MiB will not get zTOCs created for them. The index builder sets the min-layer-size to 0 - https://github.com/aws-ia/cfn-ecr-aws-soci-index-builder/blob/3c562dc3d0534206546de9e786c61342ac95f5b7/functions/source/soci-index-generator-lambda/handler.go#L273 ideally, the CLI and the index builder should have the same defaults.
 
## Expected Behavior
 
The SOCI CLI and Index Builder should have the same defaults for creating indexes.
 
## Current Behavior
 
Different `min-layer-size` for both the SOCI CLI and index builder.
 
## Possible Solution
 
The min-layer-size default should be the same for the CLI and the index builder.
 
## Steps to Reproduce (if applicable)
 
If you're reporting a bug, please provide steps to reproduce the issue.
 
1. 
2. 
3. 
 
## Screenshots (if applicable)
 
If you have any relevant screenshots, please attach them here.
 
## Environment
 
Please provide information about the environment in which you're experiencing the issue, including:
 
- Project version:
- Operating system:
- Browser version (if applicable):
- Any relevant hardware or software information:
 
## Additional Context
 
Please provide any additional information or context that may be helpful in resolving the issue or implementing the requested feature.

**Comment by sparr** [comment]
Do we have any insight around the original decision to set this to zero?

**Comment by turan18** [comment]
> Do we have any insight around the original decision to set this to zero?

I believe this was in part due to the fact that certain registries that don't allow pushing image manifests without any layers. Instead of blindly pushing, I think we should check if any zTOCs were created for an index after building and decide to push accordingly. I'll create an issue for this upstream.

**Comment by bgardner-noggin** [comment]
The ability to set the min layer size with an environment variable to the lambda would be good as well.

**Comment by bgardner-noggin** [comment]
Thanks, we'll be waiting for the upstream bug in go-fuse to be closed before retrying.
